jobs:
  include:
    - stage: preview
      language: node_js
      node_js:
        - "10"
      cache:
        directories:
          - "~/.npm"
          - "~/node_modules"
      install:
        - npm i -g lerna
        - lerna bootstrap
      script:
        - |
          FEATURE=$(echo $TRAVIS_PULL_REQUEST_BRANCH | sed 's/\+/-/g; s/\//-/g; s/\=/-/g')
          DEPLOYMENT=deployment-preview-$FEATURE
          DEPLOYMENT_URL="https://$DEPLOYMENT.now.sh"
          echo "this is the feature: $FEATURE"
          npm run test
          npm run build:web
          npm install now --no-save
          now -e CONTENTFUL_SPACE=$CONTENTFUL_SPACE -e CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN -e RAZZLE_CMS_NODE_URL=$RAZZLE_HOST -e RAZZLE_HOST=$RAZZLE_HOST --token $NOW_TOKEN_ITEAMSE --scope=iteam
          now alias $DEPLOYMENT --token NOW_TOKEN_ITEAMSE --scope=iteam
      after_success:
        - |
          curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
          -d "{\"body\": \"Deployment preview ready at: ${DEPLOYMENT_URL}\"}" \
          "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"

    - stage: release
      language: node_js
      node_js:
        - "10"
      cache:
        directories:
          - "~/.npm"
          - "~/node_modules"
      install:
        - npm i -g lerna
        - lerna bootstrap
      script:
        - npm run test
      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO_WEB=iteam1337/iteamse
        - export REPO_CMS=iteam1337/iteamse-cms
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
          ; fi`
        - docker build -f ./packages/iteam-se/Dockerfile -t $REPO_WEB:$TAG ./packages/iteam-se/
        - docker tag $TAG $REPO_WEB:TAG
        - docker push $REPO_WEB:$TAG
        - docker build -f ./packages/iteam-cms/Dockerfile -t $REPO_CMS:$TAG ./packages/iteam-cms/
        - docker tag $TAG $REPO_CMS:TAG
        - docker push $REPO_CMS:$TAG

stages:
  - name: preview
    if: branch = master AND type = pull_request
  - name: release
    if: branch = master AND type != pull_request

notifications:
  email: false
