// flow-typed signature: 4c2adb654ac64342e78b1e5b2f0dba66
// flow-typed version: <<STUB>>/apollo-mocknetworkinterface_v2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-mocknetworkinterface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-mocknetworkinterface' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-mocknetworkinterface/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'apollo-mocknetworkinterface/__tests__/query.graphql' {
  declare module.exports: any;
}

declare module 'apollo-mocknetworkinterface/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'apollo-mocknetworkinterface/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-mocknetworkinterface/__tests__/index.test.js' {
  declare module.exports: $Exports<'apollo-mocknetworkinterface/__tests__/index.test'>;
}
declare module 'apollo-mocknetworkinterface/__tests__/query.graphql.js' {
  declare module.exports: $Exports<'apollo-mocknetworkinterface/__tests__/query.graphql'>;
}
declare module 'apollo-mocknetworkinterface/gulpfile.babel.js' {
  declare module.exports: $Exports<'apollo-mocknetworkinterface/gulpfile.babel'>;
}
declare module 'apollo-mocknetworkinterface/lib/index.js' {
  declare module.exports: $Exports<'apollo-mocknetworkinterface/lib/index'>;
}
