// flow-typed signature: 6e1cb0dfed7b5d10b81d2e22a5f1787f
// flow-typed version: <<STUB>>/contrast_v1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contrast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contrast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contrast/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contrast/index' {
  declare module.exports: $Exports<'contrast'>;
}
declare module 'contrast/index.js' {
  declare module.exports: $Exports<'contrast'>;
}
declare module 'contrast/test.js' {
  declare module.exports: $Exports<'contrast/test'>;
}
