// flow-typed signature: fe5efeaa3db624ddbb1f29f8476aecb8
// flow-typed version: <<STUB>>/razzle_v0.8.14/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'razzle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'razzle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'razzle/babel' {
  declare module.exports: any;
}

declare module 'razzle/bin/razzle' {
  declare module.exports: any;
}

declare module 'razzle/config/createConfig' {
  declare module.exports: any;
}

declare module 'razzle/config/createJestConfig' {
  declare module.exports: any;
}

declare module 'razzle/config/env' {
  declare module.exports: any;
}

declare module 'razzle/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module 'razzle/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'razzle/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'razzle/config/paths' {
  declare module.exports: any;
}

declare module 'razzle/config/polyfills' {
  declare module.exports: any;
}

declare module 'razzle/polyfills' {
  declare module.exports: any;
}

declare module 'razzle/scripts/build' {
  declare module.exports: any;
}

declare module 'razzle/scripts/start' {
  declare module.exports: any;
}

declare module 'razzle/scripts/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'razzle/babel.js' {
  declare module.exports: $Exports<'razzle/babel'>;
}
declare module 'razzle/bin/razzle.js' {
  declare module.exports: $Exports<'razzle/bin/razzle'>;
}
declare module 'razzle/config/createConfig.js' {
  declare module.exports: $Exports<'razzle/config/createConfig'>;
}
declare module 'razzle/config/createJestConfig.js' {
  declare module.exports: $Exports<'razzle/config/createJestConfig'>;
}
declare module 'razzle/config/env.js' {
  declare module.exports: $Exports<'razzle/config/env'>;
}
declare module 'razzle/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'razzle/config/jest/babelTransform'>;
}
declare module 'razzle/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'razzle/config/jest/cssTransform'>;
}
declare module 'razzle/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'razzle/config/jest/fileTransform'>;
}
declare module 'razzle/config/paths.js' {
  declare module.exports: $Exports<'razzle/config/paths'>;
}
declare module 'razzle/config/polyfills.js' {
  declare module.exports: $Exports<'razzle/config/polyfills'>;
}
declare module 'razzle/polyfills.js' {
  declare module.exports: $Exports<'razzle/polyfills'>;
}
declare module 'razzle/scripts/build.js' {
  declare module.exports: $Exports<'razzle/scripts/build'>;
}
declare module 'razzle/scripts/start.js' {
  declare module.exports: $Exports<'razzle/scripts/start'>;
}
declare module 'razzle/scripts/test.js' {
  declare module.exports: $Exports<'razzle/scripts/test'>;
}
