// flow-typed signature: 34fae01acd0f56f0c1ab438233fdd4d0
// flow-typed version: <<STUB>>/react-reveal_v1.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-reveal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-reveal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-reveal/Animation' {
  declare module.exports: any;
}

declare module 'react-reveal/Bounce' {
  declare module.exports: any;
}

declare module 'react-reveal/debounce' {
  declare module.exports: any;
}

declare module 'react-reveal/Fade' {
  declare module.exports: any;
}

declare module 'react-reveal/Flash' {
  declare module.exports: any;
}

declare module 'react-reveal/Flip' {
  declare module.exports: any;
}

declare module 'react-reveal/globals' {
  declare module.exports: any;
}

declare module 'react-reveal/hamburger' {
  declare module.exports: any;
}

declare module 'react-reveal/HamburgerIcon' {
  declare module.exports: any;
}

declare module 'react-reveal/HeadShake' {
  declare module.exports: any;
}

declare module 'react-reveal/Jello' {
  declare module.exports: any;
}

declare module 'react-reveal/Jump' {
  declare module.exports: any;
}

declare module 'react-reveal/LightSpeed' {
  declare module.exports: any;
}

declare module 'react-reveal/makeCarousel' {
  declare module.exports: any;
}

declare module 'react-reveal/Pulse' {
  declare module.exports: any;
}

declare module 'react-reveal/responsive' {
  declare module.exports: any;
}

declare module 'react-reveal/Reveal' {
  declare module.exports: any;
}

declare module 'react-reveal/RevealBase' {
  declare module.exports: any;
}

declare module 'react-reveal/Roll' {
  declare module.exports: any;
}

declare module 'react-reveal/Rotate' {
  declare module.exports: any;
}

declare module 'react-reveal/RubberBand' {
  declare module.exports: any;
}

declare module 'react-reveal/Shake' {
  declare module.exports: any;
}

declare module 'react-reveal/Slide' {
  declare module.exports: any;
}

declare module 'react-reveal/Spin' {
  declare module.exports: any;
}

declare module 'react-reveal/src/Animation' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Bounce' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Fade' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Flip' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/LightSpeed' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Roll' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Rotate' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Slide' {
  declare module.exports: any;
}

declare module 'react-reveal/src/in-and-out/Zoom' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/debounce' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/globals' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/hamburger' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/HamburgerIcon' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/index' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/makeCarousel' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/responsive' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/Step' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/Stepper' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/swipedetect' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/throttle' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/withReveal' {
  declare module.exports: any;
}

declare module 'react-reveal/src/lib/wrap' {
  declare module.exports: any;
}

declare module 'react-reveal/src/Reveal' {
  declare module.exports: any;
}

declare module 'react-reveal/src/RevealBase' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Flash' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/HeadShake' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Jello' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Jump' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Pulse' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/RubberBand' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Shake' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Spin' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Swing' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Tada' {
  declare module.exports: any;
}

declare module 'react-reveal/src/simple/Wobble' {
  declare module.exports: any;
}

declare module 'react-reveal/Step' {
  declare module.exports: any;
}

declare module 'react-reveal/Stepper' {
  declare module.exports: any;
}

declare module 'react-reveal/Swing' {
  declare module.exports: any;
}

declare module 'react-reveal/swipedetect' {
  declare module.exports: any;
}

declare module 'react-reveal/Tada' {
  declare module.exports: any;
}

declare module 'react-reveal/throttle' {
  declare module.exports: any;
}

declare module 'react-reveal/withReveal' {
  declare module.exports: any;
}

declare module 'react-reveal/Wobble' {
  declare module.exports: any;
}

declare module 'react-reveal/wrap' {
  declare module.exports: any;
}

declare module 'react-reveal/Zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-reveal/Animation.js' {
  declare module.exports: $Exports<'react-reveal/Animation'>;
}
declare module 'react-reveal/Bounce.js' {
  declare module.exports: $Exports<'react-reveal/Bounce'>;
}
declare module 'react-reveal/debounce.js' {
  declare module.exports: $Exports<'react-reveal/debounce'>;
}
declare module 'react-reveal/Fade.js' {
  declare module.exports: $Exports<'react-reveal/Fade'>;
}
declare module 'react-reveal/Flash.js' {
  declare module.exports: $Exports<'react-reveal/Flash'>;
}
declare module 'react-reveal/Flip.js' {
  declare module.exports: $Exports<'react-reveal/Flip'>;
}
declare module 'react-reveal/globals.js' {
  declare module.exports: $Exports<'react-reveal/globals'>;
}
declare module 'react-reveal/hamburger.js' {
  declare module.exports: $Exports<'react-reveal/hamburger'>;
}
declare module 'react-reveal/HamburgerIcon.js' {
  declare module.exports: $Exports<'react-reveal/HamburgerIcon'>;
}
declare module 'react-reveal/HeadShake.js' {
  declare module.exports: $Exports<'react-reveal/HeadShake'>;
}
declare module 'react-reveal/index' {
  declare module.exports: $Exports<'react-reveal'>;
}
declare module 'react-reveal/index.js' {
  declare module.exports: $Exports<'react-reveal'>;
}
declare module 'react-reveal/Jello.js' {
  declare module.exports: $Exports<'react-reveal/Jello'>;
}
declare module 'react-reveal/Jump.js' {
  declare module.exports: $Exports<'react-reveal/Jump'>;
}
declare module 'react-reveal/LightSpeed.js' {
  declare module.exports: $Exports<'react-reveal/LightSpeed'>;
}
declare module 'react-reveal/makeCarousel.js' {
  declare module.exports: $Exports<'react-reveal/makeCarousel'>;
}
declare module 'react-reveal/Pulse.js' {
  declare module.exports: $Exports<'react-reveal/Pulse'>;
}
declare module 'react-reveal/responsive.js' {
  declare module.exports: $Exports<'react-reveal/responsive'>;
}
declare module 'react-reveal/Reveal.js' {
  declare module.exports: $Exports<'react-reveal/Reveal'>;
}
declare module 'react-reveal/RevealBase.js' {
  declare module.exports: $Exports<'react-reveal/RevealBase'>;
}
declare module 'react-reveal/Roll.js' {
  declare module.exports: $Exports<'react-reveal/Roll'>;
}
declare module 'react-reveal/Rotate.js' {
  declare module.exports: $Exports<'react-reveal/Rotate'>;
}
declare module 'react-reveal/RubberBand.js' {
  declare module.exports: $Exports<'react-reveal/RubberBand'>;
}
declare module 'react-reveal/Shake.js' {
  declare module.exports: $Exports<'react-reveal/Shake'>;
}
declare module 'react-reveal/Slide.js' {
  declare module.exports: $Exports<'react-reveal/Slide'>;
}
declare module 'react-reveal/Spin.js' {
  declare module.exports: $Exports<'react-reveal/Spin'>;
}
declare module 'react-reveal/src/Animation.js' {
  declare module.exports: $Exports<'react-reveal/src/Animation'>;
}
declare module 'react-reveal/src/in-and-out/Bounce.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Bounce'>;
}
declare module 'react-reveal/src/in-and-out/Fade.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Fade'>;
}
declare module 'react-reveal/src/in-and-out/Flip.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Flip'>;
}
declare module 'react-reveal/src/in-and-out/LightSpeed.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/LightSpeed'>;
}
declare module 'react-reveal/src/in-and-out/Roll.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Roll'>;
}
declare module 'react-reveal/src/in-and-out/Rotate.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Rotate'>;
}
declare module 'react-reveal/src/in-and-out/Slide.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Slide'>;
}
declare module 'react-reveal/src/in-and-out/Zoom.js' {
  declare module.exports: $Exports<'react-reveal/src/in-and-out/Zoom'>;
}
declare module 'react-reveal/src/lib/debounce.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/debounce'>;
}
declare module 'react-reveal/src/lib/globals.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/globals'>;
}
declare module 'react-reveal/src/lib/hamburger.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/hamburger'>;
}
declare module 'react-reveal/src/lib/HamburgerIcon.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/HamburgerIcon'>;
}
declare module 'react-reveal/src/lib/index.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/index'>;
}
declare module 'react-reveal/src/lib/makeCarousel.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/makeCarousel'>;
}
declare module 'react-reveal/src/lib/responsive.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/responsive'>;
}
declare module 'react-reveal/src/lib/Step.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/Step'>;
}
declare module 'react-reveal/src/lib/Stepper.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/Stepper'>;
}
declare module 'react-reveal/src/lib/swipedetect.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/swipedetect'>;
}
declare module 'react-reveal/src/lib/throttle.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/throttle'>;
}
declare module 'react-reveal/src/lib/withReveal.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/withReveal'>;
}
declare module 'react-reveal/src/lib/wrap.js' {
  declare module.exports: $Exports<'react-reveal/src/lib/wrap'>;
}
declare module 'react-reveal/src/Reveal.js' {
  declare module.exports: $Exports<'react-reveal/src/Reveal'>;
}
declare module 'react-reveal/src/RevealBase.js' {
  declare module.exports: $Exports<'react-reveal/src/RevealBase'>;
}
declare module 'react-reveal/src/simple/Flash.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Flash'>;
}
declare module 'react-reveal/src/simple/HeadShake.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/HeadShake'>;
}
declare module 'react-reveal/src/simple/Jello.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Jello'>;
}
declare module 'react-reveal/src/simple/Jump.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Jump'>;
}
declare module 'react-reveal/src/simple/Pulse.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Pulse'>;
}
declare module 'react-reveal/src/simple/RubberBand.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/RubberBand'>;
}
declare module 'react-reveal/src/simple/Shake.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Shake'>;
}
declare module 'react-reveal/src/simple/Spin.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Spin'>;
}
declare module 'react-reveal/src/simple/Swing.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Swing'>;
}
declare module 'react-reveal/src/simple/Tada.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Tada'>;
}
declare module 'react-reveal/src/simple/Wobble.js' {
  declare module.exports: $Exports<'react-reveal/src/simple/Wobble'>;
}
declare module 'react-reveal/Step.js' {
  declare module.exports: $Exports<'react-reveal/Step'>;
}
declare module 'react-reveal/Stepper.js' {
  declare module.exports: $Exports<'react-reveal/Stepper'>;
}
declare module 'react-reveal/Swing.js' {
  declare module.exports: $Exports<'react-reveal/Swing'>;
}
declare module 'react-reveal/swipedetect.js' {
  declare module.exports: $Exports<'react-reveal/swipedetect'>;
}
declare module 'react-reveal/Tada.js' {
  declare module.exports: $Exports<'react-reveal/Tada'>;
}
declare module 'react-reveal/throttle.js' {
  declare module.exports: $Exports<'react-reveal/throttle'>;
}
declare module 'react-reveal/withReveal.js' {
  declare module.exports: $Exports<'react-reveal/withReveal'>;
}
declare module 'react-reveal/Wobble.js' {
  declare module.exports: $Exports<'react-reveal/Wobble'>;
}
declare module 'react-reveal/wrap.js' {
  declare module.exports: $Exports<'react-reveal/wrap'>;
}
declare module 'react-reveal/Zoom.js' {
  declare module.exports: $Exports<'react-reveal/Zoom'>;
}
