// flow-typed signature: 2dbd189e44cde0d2a7c3dfd58f9fc857
// flow-typed version: <<STUB>>/react-safe_v1.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-safe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-safe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-safe/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-safe/index' {
  declare module.exports: $Exports<'react-safe'>;
}
declare module 'react-safe/index.js' {
  declare module.exports: $Exports<'react-safe'>;
}
declare module 'react-safe/src/index.js' {
  declare module.exports: $Exports<'react-safe/src/index'>;
}
