// flow-typed signature: 084b4c8e219b0b67104ab094735a42a2
// flow-typed version: <<STUB>>/serialize_v0.1.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serialize/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serialize/index' {
  declare module.exports: $Exports<'serialize'>;
}
declare module 'serialize/index.js' {
  declare module.exports: $Exports<'serialize'>;
}
declare module 'serialize/test.js' {
  declare module.exports: $Exports<'serialize/test'>;
}
