// flow-typed signature: c1c56fdb17311ccbbe8552c555799b16
// flow-typed version: <<STUB>>/telefonnummer_v1.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'telefonnummer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'telefonnummer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'telefonnummer/dist/areaCode' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/index' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/numberingArea' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/parser' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/riktnummer' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/utils/areaCodeDigitCount' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/utils/comparePhoneNumbers' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/utils/makeRegex' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/utils/normalize' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/utils/numberReplace' {
  declare module.exports: any;
}

declare module 'telefonnummer/dist/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'telefonnummer/dist/areaCode.js' {
  declare module.exports: $Exports<'telefonnummer/dist/areaCode'>;
}
declare module 'telefonnummer/dist/index.js' {
  declare module.exports: $Exports<'telefonnummer/dist/index'>;
}
declare module 'telefonnummer/dist/numberingArea.js' {
  declare module.exports: $Exports<'telefonnummer/dist/numberingArea'>;
}
declare module 'telefonnummer/dist/parser.js' {
  declare module.exports: $Exports<'telefonnummer/dist/parser'>;
}
declare module 'telefonnummer/dist/riktnummer.js' {
  declare module.exports: $Exports<'telefonnummer/dist/riktnummer'>;
}
declare module 'telefonnummer/dist/utils/areaCodeDigitCount.js' {
  declare module.exports: $Exports<'telefonnummer/dist/utils/areaCodeDigitCount'>;
}
declare module 'telefonnummer/dist/utils/comparePhoneNumbers.js' {
  declare module.exports: $Exports<'telefonnummer/dist/utils/comparePhoneNumbers'>;
}
declare module 'telefonnummer/dist/utils/makeRegex.js' {
  declare module.exports: $Exports<'telefonnummer/dist/utils/makeRegex'>;
}
declare module 'telefonnummer/dist/utils/normalize.js' {
  declare module.exports: $Exports<'telefonnummer/dist/utils/normalize'>;
}
declare module 'telefonnummer/dist/utils/numberReplace.js' {
  declare module.exports: $Exports<'telefonnummer/dist/utils/numberReplace'>;
}
declare module 'telefonnummer/dist/validator.js' {
  declare module.exports: $Exports<'telefonnummer/dist/validator'>;
}
