// flow-typed signature: 3b4c8525cfe15bc469392fc4ecb6b644
// flow-typed version: <<STUB>>/what-input_v5.0.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'what-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'what-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'what-input/dist/lte-IE8' {
  declare module.exports: any;
}

declare module 'what-input/dist/what-input' {
  declare module.exports: any;
}

declare module 'what-input/dist/what-input.min' {
  declare module.exports: any;
}

declare module 'what-input/Gulpfile' {
  declare module.exports: any;
}

declare module 'what-input/src/scripts/polyfills/ie8/EventListener' {
  declare module.exports: any;
}

declare module 'what-input/src/scripts/polyfills/ie8/indexOf' {
  declare module.exports: any;
}

declare module 'what-input/src/scripts/what-input' {
  declare module.exports: any;
}

// Filename aliases
declare module 'what-input/dist/lte-IE8.js' {
  declare module.exports: $Exports<'what-input/dist/lte-IE8'>;
}
declare module 'what-input/dist/what-input.js' {
  declare module.exports: $Exports<'what-input/dist/what-input'>;
}
declare module 'what-input/dist/what-input.min.js' {
  declare module.exports: $Exports<'what-input/dist/what-input.min'>;
}
declare module 'what-input/Gulpfile.js' {
  declare module.exports: $Exports<'what-input/Gulpfile'>;
}
declare module 'what-input/src/scripts/polyfills/ie8/EventListener.js' {
  declare module.exports: $Exports<'what-input/src/scripts/polyfills/ie8/EventListener'>;
}
declare module 'what-input/src/scripts/polyfills/ie8/indexOf.js' {
  declare module.exports: $Exports<'what-input/src/scripts/polyfills/ie8/indexOf'>;
}
declare module 'what-input/src/scripts/what-input.js' {
  declare module.exports: $Exports<'what-input/src/scripts/what-input'>;
}
