const teamMembers = {
  'adam': 'and',
  'alexander': 'acr',
  'amir': 'ara',
  'anders': 'abo',
  'andre': 'aeo',
  'andreas': 'apn',
  'annie': 'atl',
  'christian': 'cln',
  'dennis': 'dpn',
  'einar': 'epn',
  'emmaklara': 'ewr',
  'fanny': 'fnd',
  'hans': 'hrn',
  'indal': 'ail',
  'jimmy': 'jjd',
  'johan': 'jok',
  'johanna': 'jmn',
  'jonna': 'jhn',
  'kiwi': 'khg',
  'kristina': 'khn',
  'maria': 'mrs',
  'maria-c': 'mcl',
  'martin': 'mln',
  'mats': 'met',
  'mikael': 'mgb',
  'nils': 'nin',
  'radu': 'ram',
  'rasmus': 'rfr',
  'rebecca': 'rnn',
  'rickard': 'rln',
  'rost': 'mrt',
  'sebastian': 'san',
  'simon': 'sll',
}

export default teamMembers
