const teamMembers = {
  "adam": 'and',
  "alexander": 'acr',
  "amir": 'ara',
  "andreas": 'apn',
  "annie": 'atl',
  "christian": 'cln',
  "dennis": 'dpn',
  "einar": 'epn',
  'emmaklara': 'ewr',
  'fanny': 'fnd',
  'hans': 'hrn',
  'indal': 'ail',
  'jimmy': 'jjd',
  'johan': 'jok',
  'johanna': 'jmn',
  'jonna': 'jhn',
  'kiwi': 'khg',
  'maria': 'mrs',
  'maria-c': 'mcl',
  'martin': 'mln',
  'nils': 'nin',
  'rasmus': 'rfr',
  'rebecca': 'rnn',
  'rickard': 'rln',
  'rost': 'mrt',
  'simon': 'sll',
  'anders': 'abo',
  'andre': 'aeo',
  'kristina': 'khn',
  'mats': 'met',
  'mikael': 'mgb',
  'radu': 'ram',
  'sebastian': 'san',
}

export default teamMembers
